insert into note_type (id, name, active) values (1, 'Privada', true);
insert into note_type (id, name, active) values (2, 'Pública', true);
insert into note_type (id, name, active) values (3, 'Protegida', true);
insert into note_type (id, name, active) values (4, 'Deprecada', true);

insert into status (id, name) values (1, 'Ingresada');
insert into status (id, name) values (2, 'Aceptada');
insert into status (id, name) values (3, 'En Revisión');

insert into country (id, name, flag, prefix) values (1, 'Afganistán', null, 93);
insert into country (id, name, flag, prefix) values (2, 'Albania', null, 355);
insert into country (id, name, flag, prefix) values (3, 'Alemania', null, 49);
insert into country (id, name, flag, prefix) values (4, 'Andorra', null, 376);
insert into country (id, name, flag, prefix) values (5, 'Angola', null, 244);
insert into country (id, name, flag, prefix) values (6, 'Anguila', null, 264);
insert into country (id, name, flag, prefix) values (7, 'Antártida', null, 672);
insert into country (id, name, flag, prefix) values (8, 'Antigua y Barbuda', null, 268);
insert into country (id, name, flag, prefix) values (9, 'Arabia Saudita', null, 966);
insert into country (id, name, flag, prefix) values (10, 'Argelia', null, 213);
insert into country (id, name, flag, prefix) values (11, 'Argentina', null, 54);
insert into country (id, name, flag, prefix) values (12, 'Armenia', null, 374);
insert into country (id, name, flag, prefix) values (13, 'Aruba', null, 297);
insert into country (id, name, flag, prefix) values (14, 'Australia', null, 61);
insert into country (id, name, flag, prefix) values (15, 'Austria', null, 43);
insert into country (id, name, flag, prefix) values (16, 'Azerbaiyán', null, 994);
insert into country (id, name, flag, prefix) values (17, 'Bélgica', null, 32);
insert into country (id, name, flag, prefix) values (18, 'Bahamas', null, 242);
insert into country (id, name, flag, prefix) values (19, 'Bahrein', null, 973);
insert into country (id, name, flag, prefix) values (20, 'Bangladesh', null, 880);
insert into country (id, name, flag, prefix) values (21, 'Barbados', null, 246);
insert into country (id, name, flag, prefix) values (22, 'Belice', null, 501);
insert into country (id, name, flag, prefix) values (23, 'Benín', null, 229);
insert into country (id, name, flag, prefix) values (24, 'Bhután', null, 975);
insert into country (id, name, flag, prefix) values (25, 'Bielorrusia', null, 375);
insert into country (id, name, flag, prefix) values (26, 'Birmania', null, 95);
insert into country (id, name, flag, prefix) values (27, 'Bolivia', null, 591);
insert into country (id, name, flag, prefix) values (28, 'Bosnia y Herzegovina', null, 387);
insert into country (id, name, flag, prefix) values (29, 'Botsuana', null, 267);
insert into country (id, name, flag, prefix) values (30, 'Brasil', null, 55);
insert into country (id, name, flag, prefix) values (31, 'Brunéi', null, 673);
insert into country (id, name, flag, prefix) values (32, 'Bulgaria', null, 359);
insert into country (id, name, flag, prefix) values (33, 'Burkina Faso', null, 226);
insert into country (id, name, flag, prefix) values (34, 'Burundi', null, 257);
insert into country (id, name, flag, prefix) values (35, 'Cabo Verde', null, 238);
insert into country (id, name, flag, prefix) values (36, 'Camboya', null, 855);
insert into country (id, name, flag, prefix) values (37, 'Camerún', null, 237);
insert into country (id, name, flag, prefix) values (38, 'Canadá', null, 1);
insert into country (id, name, flag, prefix) values (39, 'Chad', null, 235);
insert into country (id, name, flag, prefix) values (40, 'Chile', null, 56);
insert into country (id, name, flag, prefix) values (41, 'China', null, 86);
insert into country (id, name, flag, prefix) values (42, 'Chipre', null, 357);
insert into country (id, name, flag, prefix) values (43, 'Ciudad del Vaticano', null, 39);
insert into country (id, name, flag, prefix) values (44, 'Colombia', null, 57);
insert into country (id, name, flag, prefix) values (45, 'Comoras', null, 269);
insert into country (id, name, flag, prefix) values (46, 'República del Congo', null, 242);
insert into country (id, name, flag, prefix) values (47, 'República Democrática del Congo', null, 243);
insert into country (id, name, flag, prefix) values (48, 'Corea del Norte', null, 850);
insert into country (id, name, flag, prefix) values (49, 'Corea del Sur', null, 82);
insert into country (id, name, flag, prefix) values (50, 'Costa de Marfil', null, 225);
insert into country (id, name, flag, prefix) values (51, 'Costa Rica', null, 506);
insert into country (id, name, flag, prefix) values (52, 'Croacia', null, 385);
insert into country (id, name, flag, prefix) values (53, 'Cuba', null, 53);
insert into country (id, name, flag, prefix) values (55, 'Dinamarca', null, 45);
insert into country (id, name, flag, prefix) values (56, 'Dominica', null, 767);
insert into country (id, name, flag, prefix) values (57, 'Ecuador', null, 593);
insert into country (id, name, flag, prefix) values (58, 'Egipto', null, 20);
insert into country (id, name, flag, prefix) values (59, 'El Salvador', null, 503);
insert into country (id, name, flag, prefix) values (60, 'Emiratos Árabes Unidos', null, 971);
insert into country (id, name, flag, prefix) values (61, 'Eritrea', null, 291);
insert into country (id, name, flag, prefix) values (62, 'Eslovaquia', null, 421);
insert into country (id, name, flag, prefix) values (63, 'Eslovenia', null, 386);
insert into country (id, name, flag, prefix) values (64, 'España', null, 34);
insert into country (id, name, flag, prefix) values (65, 'Estados Unidos de América', null, 1);
insert into country (id, name, flag, prefix) values (66, 'Estonia', null, 372);
insert into country (id, name, flag, prefix) values (67, 'Etiopía', null, 251);
insert into country (id, name, flag, prefix) values (68, 'Filipinas', null, 63);
insert into country (id, name, flag, prefix) values (69, 'Finlandia', null, 358);
insert into country (id, name, flag, prefix) values (70, 'Fiyi', null, 679);
insert into country (id, name, flag, prefix) values (71, 'Francia', null, 33);
insert into country (id, name, flag, prefix) values (72, 'Gabón', null, 241);
insert into country (id, name, flag, prefix) values (73, 'Gambia', null, 220);
insert into country (id, name, flag, prefix) values (74, 'Georgia', null, 995);
insert into country (id, name, flag, prefix) values (75, 'Ghana', null, 233);
insert into country (id, name, flag, prefix) values (76, 'Gibraltar', null, 350);
insert into country (id, name, flag, prefix) values (77, 'Granada', null, 473);
insert into country (id, name, flag, prefix) values (78, 'Grecia', null, 30);
insert into country (id, name, flag, prefix) values (79, 'Groenlandia', null, 299);
insert into country (id, name, flag, prefix) values (80, 'Guadalupe', null, 590);
insert into country (id, name, flag, prefix) values (81, 'Guam', null, 671);
insert into country (id, name, flag, prefix) values (82, 'Guatemala', null, 502);
insert into country (id, name, flag, prefix) values (83, 'Guayana Francesa', null, 594);
insert into country (id, name, flag, prefix) values (84, 'Guernsey', null, 44);
insert into country (id, name, flag, prefix) values (85, 'Guinea', null, 224);
insert into country (id, name, flag, prefix) values (86, 'Guinea Ecuatorial', null, 240);
insert into country (id, name, flag, prefix) values (87, 'Guinea-Bissau', null, 245);
insert into country (id, name, flag, prefix) values (88, 'Guyana', null, 592);
insert into country (id, name, flag, prefix) values (89, 'Haití', null, 509);
insert into country (id, name, flag, prefix) values (90, 'Honduras', null, 504);
insert into country (id, name, flag, prefix) values (91, 'Hong kong', null, 852);
insert into country (id, name, flag, prefix) values (92, 'Hungría', null, 36);
insert into country (id, name, flag, prefix) values (93, 'India', null, 91);
insert into country (id, name, flag, prefix) values (94, 'Indonesia', null, 62);
insert into country (id, name, flag, prefix) values (95, 'Irán', null, 98);
insert into country (id, name, flag, prefix) values (96, 'Irak', null, 964);
insert into country (id, name, flag, prefix) values (97, 'Irlanda', null, 353);
insert into country (id, name, flag, prefix) values (99, 'Isla de Man', null, 44);
insert into country (id, name, flag, prefix) values (100, 'Isla de Navidad', null, 61);
insert into country (id, name, flag, prefix) values (101, 'Isla Norfolk', null, 672);
insert into country (id, name, flag, prefix) values (102, 'Islandia', null, 354);
insert into country (id, name, flag, prefix) values (103, 'Islas Bermudas', null, 441);
insert into country (id, name, flag, prefix) values (104, 'Islas Caimán', null, 345);
insert into country (id, name, flag, prefix) values (105, 'Islas Cocos (Keeling)', null, 61);
insert into country (id, name, flag, prefix) values (106, 'Islas Cook', null, 682);
insert into country (id, name, flag, prefix) values (107, 'Islas de Åland', null, 358);
insert into country (id, name, flag, prefix) values (108, 'Islas Feroe', null, 298);
insert into country (id, name, flag, prefix) values (109, 'Islas Georgias del Sur y Sandwich del Sur', null, 500);
insert into country (id, name, flag, prefix) values (111, 'Islas Maldivas', null, 960);
insert into country (id, name, flag, prefix) values (112, 'Islas Malvinas', null, 500);
insert into country (id, name, flag, prefix) values (113, 'Islas Marianas del Norte', null, 670);
insert into country (id, name, flag, prefix) values (114, 'Islas Marshall', null, 692);
insert into country (id, name, flag, prefix) values (115, 'Islas Pitcairn', null, 870);
insert into country (id, name, flag, prefix) values (116, 'Islas Salomón', null, 677);
insert into country (id, name, flag, prefix) values (117, 'Islas Turcas y Caicos', null, 649);
insert into country (id, name, flag, prefix) values (118, 'Islas Ultramarinas Menores de Estados Unidos', null, 246);
insert into country (id, name, flag, prefix) values (119, 'Islas Vírgenes Británicas', null, 284);
insert into country (id, name, flag, prefix) values (120, 'Islas Vírgenes de los Estados Unidos', null, 340);
insert into country (id, name, flag, prefix) values (121, 'Israel', null, 972);
insert into country (id, name, flag, prefix) values (122, 'Italia', null, 39);
insert into country (id, name, flag, prefix) values (123, 'Jamaica', null, 876);
insert into country (id, name, flag, prefix) values (124, 'Japón', null, 81);
insert into country (id, name, flag, prefix) values (125, 'Jersey', null, 44);
insert into country (id, name, flag, prefix) values (126, 'Jordania', null, 962);
insert into country (id, name, flag, prefix) values (127, 'Kazajistán', null, 7);
insert into country (id, name, flag, prefix) values (128, 'Kenia', null, 254);
insert into country (id, name, flag, prefix) values (129, 'Kirguistán', null, 996);
insert into country (id, name, flag, prefix) values (130, 'Kiribati', null, 686);
insert into country (id, name, flag, prefix) values (131, 'Kuwait', null, 965);
insert into country (id, name, flag, prefix) values (132, 'Líbano', null, 961);
insert into country (id, name, flag, prefix) values (133, 'Laos', null, 856);
insert into country (id, name, flag, prefix) values (134, 'Lesoto', null, 266);
insert into country (id, name, flag, prefix) values (135, 'Letonia', null, 371);
insert into country (id, name, flag, prefix) values (136, 'Liberia', null, 231);
insert into country (id, name, flag, prefix) values (137, 'Libia', null, 218);
insert into country (id, name, flag, prefix) values (138, 'Liechtenstein', null, 423);
insert into country (id, name, flag, prefix) values (139, 'Lituania', null, 370);
insert into country (id, name, flag, prefix) values (140, 'Luxemburgo', null, 352);
insert into country (id, name, flag, prefix) values (141, 'México', null, 52);
insert into country (id, name, flag, prefix) values (142, 'Mónaco', null, 377);
insert into country (id, name, flag, prefix) values (143, 'Macao', null, 853);
insert into country (id, name, flag, prefix) values (144, 'Macedônia', null, 389);
insert into country (id, name, flag, prefix) values (145, 'Madagascar', null, 261);
insert into country (id, name, flag, prefix) values (146, 'Malasia', null, 60);
insert into country (id, name, flag, prefix) values (147, 'Malawi', null, 265);
insert into country (id, name, flag, prefix) values (148, 'Mali', null, 223);
insert into country (id, name, flag, prefix) values (149, 'Malta', null, 356);
insert into country (id, name, flag, prefix) values (150, 'Marruecos', null, 212);
insert into country (id, name, flag, prefix) values (151, 'Martinica', null, 596);
insert into country (id, name, flag, prefix) values (152, 'Mauricio', null, 230);
insert into country (id, name, flag, prefix) values (153, 'Mauritania', null, 222);
insert into country (id, name, flag, prefix) values (154, 'Mayotte', null, 262);
insert into country (id, name, flag, prefix) values (155, 'Micronesia', null, 691);
insert into country (id, name, flag, prefix) values (156, 'Moldavia', null, 373);
insert into country (id, name, flag, prefix) values (157, 'Mongolia', null, 976);
insert into country (id, name, flag, prefix) values (158, 'Montenegro', null, 382);
insert into country (id, name, flag, prefix) values (159, 'Montserrat', null, 664);
insert into country (id, name, flag, prefix) values (160, 'Mozambique', null, 258);
insert into country (id, name, flag, prefix) values (161, 'Namibia', null, 264);
insert into country (id, name, flag, prefix) values (162, 'Nauru', null, 674);
insert into country (id, name, flag, prefix) values (163, 'Nepal', null, 977);
insert into country (id, name, flag, prefix) values (164, 'Nicaragua', null, 505);
insert into country (id, name, flag, prefix) values (165, 'Niger', null, 227);
insert into country (id, name, flag, prefix) values (166, 'Nigeria', null, 234);
insert into country (id, name, flag, prefix) values (167, 'Niue', null, 683);
insert into country (id, name, flag, prefix) values (168, 'Noruega', null, 47);
insert into country (id, name, flag, prefix) values (169, 'Nueva Caledonia', null, 687);
insert into country (id, name, flag, prefix) values (170, 'Nueva Zelanda', null, 64);
insert into country (id, name, flag, prefix) values (171, 'Omán', null, 968);
insert into country (id, name, flag, prefix) values (172, 'Países Bajos', null, 31);
insert into country (id, name, flag, prefix) values (173, 'Pakistán', null, 92);
insert into country (id, name, flag, prefix) values (174, 'Palau', null, 680);
insert into country (id, name, flag, prefix) values (175, 'Palestina', null, 970);
insert into country (id, name, flag, prefix) values (176, 'Panamá', null, 507);
insert into country (id, name, flag, prefix) values (177, 'Papúa Nueva Guinea', null, 675);
insert into country (id, name, flag, prefix) values (178, 'Paraguay', null, 595);
insert into country (id, name, flag, prefix) values (179, 'Perú', null, 51);
insert into country (id, name, flag, prefix) values (180, 'Polinesia Francesa', null, 689);
insert into country (id, name, flag, prefix) values (181, 'Polonia', null, 48);
insert into country (id, name, flag, prefix) values (182, 'Portugal', null, 351);
insert into country (id, name, flag, prefix) values (183, 'Puerto Rico', null, 1);
insert into country (id, name, flag, prefix) values (184, 'Qatar', null, 974);
insert into country (id, name, flag, prefix) values (185, 'Reino Unido', null, 44);
insert into country (id, name, flag, prefix) values (186, 'República Centroafricana', null, 236);
insert into country (id, name, flag, prefix) values (187, 'República Checa', null, 420);
insert into country (id, name, flag, prefix) values (188, 'República Dominicana', null, 809);
insert into country (id, name, flag, prefix) values (189, 'República de Sudán del Sur', null, 211);
insert into country (id, name, flag, prefix) values (190, 'Reunión', null, 262);
insert into country (id, name, flag, prefix) values (191, 'Ruanda', null, 250);
insert into country (id, name, flag, prefix) values (192, 'Rumanía', null, 40);
insert into country (id, name, flag, prefix) values (193, 'Rusia', null, 7);
insert into country (id, name, flag, prefix) values (194, 'Sahara Occidental', null, 212);
insert into country (id, name, flag, prefix) values (195, 'Samoa', null, 685);
insert into country (id, name, flag, prefix) values (196, 'Samoa Americana', null, 684);
insert into country (id, name, flag, prefix) values (197, 'San Bartolomé', null, 590);
insert into country (id, name, flag, prefix) values (198, 'San Cristóbal y Nieves', null, 869);
insert into country (id, name, flag, prefix) values (199, 'San Marino', null, 378);
insert into country (id, name, flag, prefix) values (200, 'San Martín (Francia)', null, 599);
insert into country (id, name, flag, prefix) values (201, 'San Pedro y Miquelón', null, 508);
insert into country (id, name, flag, prefix) values (202, 'San Vicente y las Granadinas', null, 784);
insert into country (id, name, flag, prefix) values (203, 'Santa Elena', null, 290);
insert into country (id, name, flag, prefix) values (204, 'Santa Lucía', null, 758);
insert into country (id, name, flag, prefix) values (205, 'Santo Tomé y Príncipe', null, 239);
insert into country (id, name, flag, prefix) values (206, 'Senegal', null, 221);
insert into country (id, name, flag, prefix) values (207, 'Serbia', null, 381);
insert into country (id, name, flag, prefix) values (208, 'Seychelles', null, 248);
insert into country (id, name, flag, prefix) values (209, 'Sierra Leona', null, 232);
insert into country (id, name, flag, prefix) values (210, 'Singapur', null, 65);
insert into country (id, name, flag, prefix) values (211, 'Sint Maarten', null, 721);
insert into country (id, name, flag, prefix) values (212, 'Siria', null, 963);
insert into country (id, name, flag, prefix) values (213, 'Somalia', null, 252);
insert into country (id, name, flag, prefix) values (214, 'Sri lanka', null, 94);
insert into country (id, name, flag, prefix) values (215, 'Sudáfrica', null, 27);
insert into country (id, name, flag, prefix) values (216, 'Sudán', null, 249);
insert into country (id, name, flag, prefix) values (217, 'Suecia', null, 46);
insert into country (id, name, flag, prefix) values (218, 'Suiza', null, 41);
insert into country (id, name, flag, prefix) values (219, 'Surinám', null, 597);
insert into country (id, name, flag, prefix) values (220, 'Svalbard y Jan Mayen', null, 47);
insert into country (id, name, flag, prefix) values (221, 'Swazilandia', null, 268);
insert into country (id, name, flag, prefix) values (222, 'Tayikistán', null, 992);
insert into country (id, name, flag, prefix) values (223, 'Tailandia', null, 66);
insert into country (id, name, flag, prefix) values (224, 'Taiwán', null, 886);
insert into country (id, name, flag, prefix) values (225, 'Tanzania', null, 255);
insert into country (id, name, flag, prefix) values (226, 'Territorio Británico del Océano Índico', null, 246);
insert into country (id, name, flag, prefix) values (228, 'Timor Oriental', null, 670);
insert into country (id, name, flag, prefix) values (229, 'Togo', null, 228);
insert into country (id, name, flag, prefix) values (230, 'Tokelau', null, 690);
insert into country (id, name, flag, prefix) values (231, 'Tonga', null, 676);
insert into country (id, name, flag, prefix) values (232, 'Trinidad y Tobago', null, 868);
insert into country (id, name, flag, prefix) values (233, 'Tunez', null, 216);
insert into country (id, name, flag, prefix) values (234, 'Turkmenistán', null, 993);
insert into country (id, name, flag, prefix) values (235, 'Turquía', null, 90);
insert into country (id, name, flag, prefix) values (236, 'Tuvalu', null, 688);
insert into country (id, name, flag, prefix) values (237, 'Ucrania', null, 380);
insert into country (id, name, flag, prefix) values (238, 'Uganda', null, 256);
insert into country (id, name, flag, prefix) values (239, 'Uruguay', null, 598);
insert into country (id, name, flag, prefix) values (240, 'Uzbekistán', null, 998);
insert into country (id, name, flag, prefix) values (241, 'Vanuatu', null, 678);
insert into country (id, name, flag, prefix) values (242, 'Venezuela', null, 58);
insert into country (id, name, flag, prefix) values (243, 'Vietnam', null, 84);
insert into country (id, name, flag, prefix) values (244, 'Wallis y Futuna', null, 681);
insert into country (id, name, flag, prefix) values (245, 'Yemen', null, 967);
insert into country (id, name, flag, prefix) values (246, 'Yibuti', null, 253);
insert into country (id, name, flag, prefix) values (247, 'Zambia', null, 260);
insert into country (id, name, flag, prefix) values (248, 'Zimbabue', null, 263);


INSERT INTO category (user_id, "label_id", "name" , active) values
(13, 1, 'Recordatorio', true),
(14, 1, 'Recordatorio', true),
(15, 1, 'Recordatorio', false),
(16, 1, 'Recordatorio',true),
(17, 1, 'Recordatorio',false),
(18, 1, 'Recordatorio',true),
(19, 1, 'Aniversario',true),
(20, 1, 'Aniversario',false),
(21, 1, 'Aniversario',true),
(22, 1, 'Aniversario',true),
(23, 1, 'Cumpleaños',false),
(24, 1, 'Cumpleaños',true),
(25, 1, 'Cumpleaños',false),
(26, 1, 'Cumpleaños',true)

